# Generated by Django 4.0.3 on 2022-04-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_customerprofile_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='mudi'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='city',
            field=models.CharField(default='Najing', max_length=20),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='country',
            field=models.CharField(default='China', max_length=10),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='detailed_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Secret', 'Secret')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='phone_number',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='state_or_province',
            field=models.CharField(default='Jiangsu', max_length=20),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='zip_code',
            field=models.IntegerField(default=210010),
        ),
    ]
