# Generated by Django 4.0.3 on 2022-04-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_useraccount_city_remove_useraccount_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_number', models.CharField(max_length=15, null=True, unique=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='mudi')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Secret', 'Secret')], max_length=10, null=True)),
                ('email_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='email_verified',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='phone_number',
        ),
    ]
