# Generated by Django 4.0.3 on 2022-04-30 14:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_useraccount_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='id',
            field=models.UUIDField(default=uuid.UUID('84e6b6a6-dd23-4ff0-945b-7c8b910e668f'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('058fdec3-fdbc-4529-9e54-865810056cb0'), primary_key=True, serialize=False),
        ),
    ]
