# Generated by Django 4.0.3 on 2022-04-30 14:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_useraccount_id_alter_userprofile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d77324ea-9f70-42d4-a0b1-71b67eec514b'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('39d87a4c-1fa8-4a40-8e6b-09971b72ca0c'), primary_key=True, serialize=False),
        ),
    ]
