# Generated by Django 4.0.3 on 2022-05-01 01:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_useraccount_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='id',
            field=models.UUIDField(default=uuid.UUID('27381651-90a7-404b-82a8-9c05cd09d42f'), primary_key=True, serialize=False, unique=True),
        ),
    ]
