# Generated by Django 4.0.3 on 2022-05-01 01:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_useraccount_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f6504512-2e1a-4ead-a038-93d3233ab951'), primary_key=True, serialize=False, unique=True),
        ),
    ]
