# Generated by Django 4.0.3 on 2022-05-01 01:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_useraccount_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a4c5973a-f902-49be-a403-7d7c10dddc75'), primary_key=True, serialize=False, unique=True),
        ),
    ]
