# Generated by Django 4.0.3 on 2022-05-01 02:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_useraccount_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1491b4af-f739-4aa0-bbd9-50c383fd3b55'), primary_key=True, serialize=False, unique=True),
        ),
    ]
