# Generated by Django 4.0.3 on 2022-05-01 02:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_useraccount_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8ce2444a-9efd-4a50-a4e1-e58f7ca8761a'), primary_key=True, serialize=False, unique=True),
        ),
    ]
