# Generated by Django 4.0.3 on 2022-05-01 02:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_useraccount_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='id',
            field=models.UUIDField(default=uuid.UUID('54b41478-6517-41ba-b7d5-d0c7ae04e524'), primary_key=True, serialize=False, unique=True),
        ),
    ]
