# Generated by Django 4.0.3 on 2022-05-01 03:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_useraccount_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4bf75e8d-946e-4d7b-91a4-e36e604d9b1b'), primary_key=True, serialize=False, unique=True),
        ),
    ]
