# Generated by Django 4.0.3 on 2022-05-01 03:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_useraccount_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7c48e1b3-05e7-4f2a-8d91-b09d1027ce7a'), primary_key=True, serialize=False, unique=True),
        ),
    ]
