# Generated by Django 4.0.3 on 2022-05-01 03:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_useraccount_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1b49a97e-947f-4cfb-8bb7-256ce6ddb9ea'), primary_key=True, serialize=False, unique=True),
        ),
    ]
