# Generated by Django 4.0.3 on 2022-05-02 03:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_useraccount_id_alter_userprofile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b9aba2aa-758a-4067-bd39-02f60f6ce73c'), primary_key=True, serialize=False, unique=True),
        ),
    ]
