# Generated by Django 4.0.3 on 2022-05-02 03:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_alter_useraccount_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='id',
            field=models.UUIDField(default=uuid.UUID('24807c48-1733-4be0-be1b-4e9814756c27'), primary_key=True, serialize=False, unique=True),
        ),
    ]
