# Generated by Django 4.0.3 on 2022-05-07 12:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_alter_useraccount_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='id',
            field=models.UUIDField(default=uuid.UUID('16b63457-b73d-4034-8a69-bc5e1ccca04d'), primary_key=True, serialize=False, unique=True),
        ),
    ]
