# Generated by Django 4.0.3 on 2022-05-07 12:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_alter_useraccount_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8b576639-306f-4ce5-9070-4cb2dc396bab'), primary_key=True, serialize=False, unique=True),
        ),
    ]
