# Generated by Django 4.0.3 on 2022-05-07 12:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_alter_useraccount_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='id',
            field=models.UUIDField(default=uuid.UUID('81630b00-d0b9-418d-8462-6cd7b0d65980'), primary_key=True, serialize=False, unique=True),
        ),
    ]
