# Generated by Django 4.0.3 on 2022-05-08 05:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_alter_useraccount_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='id',
            field=models.UUIDField(default=uuid.UUID('755529b2-0bdd-4617-9d5d-6a7a3d197191'), primary_key=True, serialize=False, unique=True),
        ),
    ]
