# Generated by Django 4.0.3 on 2022-05-08 08:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_alter_useraccount_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9af4e85b-187e-43b8-a381-db4470159f41'), primary_key=True, serialize=False, unique=True),
        ),
    ]
