# Generated by Django 4.0.3 on 2022-05-08 09:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_alter_useraccount_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='id',
            field=models.UUIDField(default=uuid.UUID('130a07a6-fc2e-4cee-92e2-573104832885'), primary_key=True, serialize=False, unique=True),
        ),
    ]
