# Generated by Django 4.0.3 on 2022-05-09 05:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_alter_useraccount_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='id',
            field=models.UUIDField(default=uuid.UUID('01992faa-6f83-4c8f-9f2e-b6d6792d9f17'), primary_key=True, serialize=False, unique=True),
        ),
    ]
