# Generated by Django 4.0.3 on 2022-05-11 02:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_alter_useraccount_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5ddfbfac-1382-4d7d-8f3c-ca851d7397d7'), primary_key=True, serialize=False, unique=True),
        ),
    ]
