# Generated by Django 4.0.3 on 2022-05-11 10:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_alter_useraccount_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='id',
            field=models.UUIDField(default=uuid.UUID('904d1519-ac06-4a10-9c99-e4775090c0cb'), primary_key=True, serialize=False, unique=True),
        ),
    ]
