# Generated by Django 4.0.3 on 2022-05-11 11:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_alter_useraccount_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c2825856-bf85-460f-a117-fd5dc8b2c186'), primary_key=True, serialize=False, unique=True),
        ),
    ]
