# Generated by Django 4.0.3 on 2022-05-11 13:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_alter_useraccount_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='id',
            field=models.UUIDField(default=uuid.UUID('21e4c224-ba3b-44e3-be56-734b4f9255b5'), primary_key=True, serialize=False, unique=True),
        ),
    ]
