# Generated by Django 4.0.3 on 2022-05-11 13:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_alter_useraccount_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='id',
            field=models.UUIDField(default=uuid.UUID('796f7c41-c9f2-4e00-98c0-c0b097fb3c39'), primary_key=True, serialize=False, unique=True),
        ),
    ]
