# Generated by Django 4.0.3 on 2022-05-11 13:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_alter_useraccount_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0180efb5-d215-4e63-8c25-cb847c2ad129'), primary_key=True, serialize=False, unique=True),
        ),
    ]
