# Generated by Django 4.0.3 on 2022-05-11 13:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_alter_useraccount_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3b85d0c0-b1a6-4fab-bfcb-c5b46732f249'), primary_key=True, serialize=False, unique=True),
        ),
    ]
