# Generated by Django 4.0.3 on 2022-05-11 13:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0054_alter_useraccount_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='id',
            field=models.UUIDField(default=uuid.UUID('42b9d9f8-7bee-491c-a710-2ab4edc9e303'), primary_key=True, serialize=False, unique=True),
        ),
    ]
