# Generated by Django 4.0.3 on 2022-05-11 14:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0055_alter_useraccount_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3056af20-e41a-40a4-acba-124a79a7bbb4'), primary_key=True, serialize=False, unique=True),
        ),
    ]
