# Generated by Django 4.0.3 on 2022-05-11 15:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_alter_useraccount_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5b6547b3-05e3-4a5d-852b-2d8af2296db1'), primary_key=True, serialize=False, unique=True),
        ),
    ]
