# Generated by Django 4.0.3 on 2022-05-11 15:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0057_alter_useraccount_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8d8be4c4-3d6c-4e4a-a281-6ec13040d6c9'), primary_key=True, serialize=False, unique=True),
        ),
    ]
