# Generated by Django 4.0.3 on 2022-05-11 15:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0058_alter_useraccount_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e7649b52-9b29-4380-9833-50d6e119635c'), primary_key=True, serialize=False, unique=True),
        ),
    ]
