# Generated by Django 4.0.3 on 2022-05-11 15:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0059_alter_useraccount_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0c78c2dd-be1f-446f-8ccb-0a59e4e7035c'), primary_key=True, serialize=False, unique=True),
        ),
    ]
