# Generated by Django 4.0.3 on 2022-05-11 15:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0060_alter_useraccount_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0a6b8e0f-f202-4cf6-b44d-6401b50d6348'), primary_key=True, serialize=False, unique=True),
        ),
    ]
