# Generated by Django 4.0.3 on 2022-05-11 16:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0061_alter_useraccount_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='id',
            field=models.UUIDField(default=uuid.UUID('373f99f2-cff3-4058-bc14-be62b93e5df8'), primary_key=True, serialize=False, unique=True),
        ),
    ]
