# Generated by Django 4.0.3 on 2022-05-12 15:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0064_alter_useraccount_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9ef8e2ef-e6fb-44bf-b120-c53476c7041f'), primary_key=True, serialize=False, unique=True),
        ),
    ]
