# Generated by Django 4.0.3 on 2022-05-12 16:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0065_alter_useraccount_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='id',
            field=models.UUIDField(default=uuid.UUID('76ad001a-991f-4edb-aca0-dbec901042bb'), primary_key=True, serialize=False, unique=True),
        ),
    ]
