# Generated by Django 4.0.3 on 2022-05-14 21:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0068_alter_useraccount_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='id',
            field=models.UUIDField(default=uuid.UUID('490547c5-39f0-4125-a70e-ac6140e361c0'), primary_key=True, serialize=False, unique=True),
        ),
    ]
