# Generated by Django 4.0.3 on 2022-05-15 10:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0069_alter_useraccount_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='id',
            field=models.UUIDField(default=uuid.UUID('902c49c1-09e5-4ec5-ad32-c328b335bdee'), primary_key=True, serialize=False, unique=True),
        ),
    ]
