# Generated by Django 4.0.3 on 2022-05-15 11:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0070_alter_useraccount_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='id',
            field=models.UUIDField(default=uuid.UUID('55a57b30-40e2-4556-a054-b1fec9de2a38'), primary_key=True, serialize=False, unique=True),
        ),
    ]
