# Generated by Django 4.0.3 on 2022-05-15 11:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0071_alter_useraccount_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='id',
            field=models.UUIDField(default=uuid.UUID('733c03e5-876f-493c-bcb8-51096441312c'), primary_key=True, serialize=False, unique=True),
        ),
    ]
