# Generated by Django 4.0.3 on 2022-05-15 12:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0073_alter_useraccount_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='id',
            field=models.UUIDField(default=uuid.UUID('af824462-6b72-4e8e-89a5-d77b99f88b02'), primary_key=True, serialize=False, unique=True),
        ),
    ]
