# Generated by Django 4.0.3 on 2022-07-15 12:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0077_alter_useraccount_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='email',
            field=models.EmailField(blank=True, max_length=25, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3dbd872a-f4a2-4216-ba65-56c6c4e4cf55'), primary_key=True, serialize=False, unique=True),
        ),
    ]
