# Generated by Django 4.0.3 on 2022-07-15 12:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0078_alter_useraccount_email_alter_useraccount_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='id',
            field=models.UUIDField(default=uuid.UUID('40f5bbbb-da14-4a4d-ab6c-fff9a7a670e9'), primary_key=True, serialize=False, unique=True),
        ),
    ]
