# Generated by Django 4.0.3 on 2022-07-16 16:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0084_userprofile_user_alter_useraccount_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cbe7006f-cd04-4d20-b7dd-c8ab6e264436'), primary_key=True, serialize=False, unique=True),
        ),
    ]
