# Generated by Django 4.0.3 on 2022-07-16 16:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0085_alter_useraccount_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='phone_number',
            new_name='contact',
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c2022e78-a5fb-440c-a6f8-52d7868b04a9'), primary_key=True, serialize=False, unique=True),
        ),
    ]
