# Generated by Django 4.0.3 on 2022-04-18 00:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_coupon_order_payments_refund_shippingaddress_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='reference_code',
            field=models.UUIDField(default=uuid.UUID('b19b6675-164e-41db-b121-d19ef38ebb9e')),
        ),
    ]
