# Generated by Django 4.0.3 on 2022-04-18 13:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_userprofile_alter_order_reference_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.AlterField(
            model_name='order',
            name='reference_code',
            field=models.UUIDField(default=uuid.UUID('237228a0-ccbe-4d2a-a0be-3bd992517244')),
        ),
    ]
