# Generated by Django 4.0.3 on 2022-04-18 13:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_delete_userprofile_alter_order_reference_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='reference_code',
            field=models.UUIDField(default=uuid.UUID('da2e6f1a-e8ef-4a0b-8798-b02161b58f7e')),
        ),
    ]
