# Generated by Django 4.0.3 on 2022-04-19 05:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_reference_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='reference_code',
            field=models.UUIDField(default=uuid.UUID('3e152922-4654-4eb7-afbc-55481d87f378')),
        ),
    ]
