# Generated by Django 4.0.3 on 2022-04-23 14:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_order_reference_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='reference_code',
            field=models.UUIDField(default=uuid.UUID('561e0b64-4b11-4cbf-8040-ed52f84a2cdf')),
        ),
    ]
