# Generated by Django 4.0.3 on 2022-04-23 15:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_alter_order_reference_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='reference_code',
            field=models.UUIDField(default=uuid.UUID('65a9c5b5-45ff-4a17-a902-e404a36294fc')),
        ),
    ]
