# Generated by Django 4.0.3 on 2022-04-30 14:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_alter_cartitem_id_alter_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='id',
            field=models.UUIDField(default=uuid.UUID('237bb4b6-f9f3-4f86-a9d7-62996d85a0e4'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6f2fa026-fcb2-43ec-a948-f9738e62ca67'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_reference',
            field=models.UUIDField(default=uuid.UUID('aa835e99-f1c8-4106-9c18-9a920aa079eb')),
        ),
    ]
