# Generated by Django 4.0.3 on 2022-04-30 14:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_alter_cartitem_id_alter_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4d08582d-8cee-4ebd-8a59-666eca21d05f'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b0ba1636-e544-4ddb-bcb5-f1d4bd0cd8e5'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_reference',
            field=models.UUIDField(default=uuid.UUID('a404a595-6de8-4467-ad66-ddf68dcdad48')),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c1e202ae-a878-4c61-a2b9-b34be50ee540'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='id',
            field=models.UUIDField(default=uuid.UUID('45d1cbf6-ab60-4080-a987-43f80c41a327'), primary_key=True, serialize=False),
        ),
    ]
