# Generated by Django 4.0.3 on 2022-04-30 14:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_alter_cartitem_id_alter_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='id',
            field=models.UUIDField(default=uuid.UUID('634afe79-5036-4038-9e37-fd4b07916099'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.UUID('564f9efe-0564-4a2b-ba40-e9a90def4baf'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_reference',
            field=models.UUIDField(default=uuid.UUID('6936cce7-e99c-456f-b994-42ffb26ccdd5')),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2eeeec82-a3e3-4d93-901b-d8e8dc5750ad'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='id',
            field=models.UUIDField(default=uuid.UUID('17b10487-a314-4916-bc6a-64fa626c68bf'), primary_key=True, serialize=False),
        ),
    ]
