# Generated by Django 4.0.3 on 2022-04-30 15:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_alter_cartitem_id_alter_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d1f69174-c0a5-4b22-85f3-c5b87d5f7f33'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e4540c44-9815-4354-9a11-50c183dfee33'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_reference',
            field=models.UUIDField(default=uuid.UUID('6dc00eeb-38a1-44fa-ba3e-4ecca42b5842')),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6e172cc6-b9b5-428b-8033-ee9ba41f0955'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='id',
            field=models.UUIDField(default=uuid.UUID('83349945-08ff-4f61-b98c-7512bd213066'), primary_key=True, serialize=False),
        ),
    ]
