# Generated by Django 4.0.3 on 2022-05-01 01:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_alter_cartitem_id_alter_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5ae17c6c-b6b7-414a-9cb3-ba75549c043b'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f3373f7c-2c2d-4637-88ac-1dc61d91229b'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_reference',
            field=models.UUIDField(default=uuid.UUID('4dfe579b-ad92-43b6-8921-983f900b40ab')),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5b1e5e1c-6ad5-4ef7-9515-123b2b270a56'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c1ee173e-702a-4df5-8783-e4568fa07a57'), primary_key=True, serialize=False),
        ),
    ]
