# Generated by Django 4.0.3 on 2022-05-01 01:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_alter_cartitem_id_alter_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2b3077de-1ce8-4474-a54e-2d16d4f4f12c'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.UUID('85355517-90fa-4310-bd6c-2f492a7f4b08'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_reference',
            field=models.UUIDField(default=uuid.UUID('0f2e1117-4fcb-4a8b-8548-94e3e42c42bf')),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='id',
            field=models.UUIDField(default=uuid.UUID('bec3b41b-aa86-4f8c-a593-3f6134ee0e03'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5b289639-c38d-46c5-833d-5d3241b3d5de'), primary_key=True, serialize=False),
        ),
    ]
