# Generated by Django 4.0.3 on 2022-05-01 01:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0032_alter_cartitem_id_alter_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='id',
            field=models.UUIDField(default=uuid.UUID('03f0db92-2c24-4204-8914-b9af6c53126f'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4b9688b2-70ea-47e2-a865-c05ffadbc04d'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_reference',
            field=models.UUIDField(default=uuid.UUID('1e97eeeb-3231-4bed-99df-78d802fe4deb')),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2054e025-301e-4828-8a91-d88a2f43f6f8'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4bb3ee9d-0619-45c3-8147-23c3aa53093d'), primary_key=True, serialize=False),
        ),
    ]
