# Generated by Django 4.0.3 on 2022-05-01 02:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0033_alter_cartitem_id_alter_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='id',
            field=models.UUIDField(default=uuid.UUID('24c9e537-e9ca-48b9-8654-2294cc3d10d6'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.UUID('aea6b2e5-f09b-46da-b168-5c28402ae2ad'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_reference',
            field=models.UUIDField(default=uuid.UUID('acfac53b-2671-4aff-a783-687fd7aa2d19')),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='id',
            field=models.UUIDField(default=uuid.UUID('bf8b1c45-97a7-4d2d-b08f-8a2d5a13ff88'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='id',
            field=models.UUIDField(default=uuid.UUID('da970fd4-70bd-4f06-b8e4-f8396b10a2ad'), primary_key=True, serialize=False),
        ),
    ]
