# Generated by Django 4.0.3 on 2022-05-01 02:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0034_alter_cartitem_id_alter_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7b03c450-977a-4945-9ea2-efff4d244723'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b4566eb2-2b30-488c-987e-cf2926a12c75'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_reference',
            field=models.UUIDField(default=uuid.UUID('e14bdc2d-f06c-4afc-903c-b1c8c52260c3')),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d4bab4c9-10c3-4e5f-a65c-755670df6001'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f6034896-5e85-4d46-b769-544cc339b868'), primary_key=True, serialize=False),
        ),
    ]
