# Generated by Django 4.0.3 on 2022-05-01 02:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0035_alter_cartitem_id_alter_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0da557f9-afa6-40a2-a97f-70a176e487bb'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.UUID('27fa0521-3297-4c29-9e45-63af7a810e59'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_reference',
            field=models.UUIDField(default=uuid.UUID('d36ebba1-4d62-4c86-8613-faf22da0c916')),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b5351ab2-d7b2-427f-b6c2-7466ae1f858c'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9f4f172a-81e4-41e3-853e-8f3c7b5d8171'), primary_key=True, serialize=False),
        ),
    ]
