# Generated by Django 4.0.3 on 2022-05-01 02:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0036_alter_cartitem_id_alter_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='id',
            field=models.UUIDField(default=uuid.UUID('776494f1-239a-4a2d-81bc-1574e5b8efa1'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.UUID('515a8a31-e4ef-4ae6-853f-f4c2b05c1b52'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_reference',
            field=models.UUIDField(default=uuid.UUID('d64abdfc-53dd-4935-873f-3267541da00e')),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='id',
            field=models.UUIDField(default=uuid.UUID('bf4cb525-7d88-44b3-8de0-35523bbc0d6f'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='id',
            field=models.UUIDField(default=uuid.UUID('74ef473b-0110-4c0a-8075-4cb23639d3f4'), primary_key=True, serialize=False),
        ),
    ]
