# Generated by Django 4.0.3 on 2022-05-01 03:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0038_alter_cartitem_id_alter_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0a5b1cd3-8185-4585-a3c6-a65eb80d9fdf'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ae1accff-97c0-44fb-b661-335ea1772618'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_reference',
            field=models.UUIDField(default=uuid.UUID('d7c57936-f280-4feb-a11e-016c5c77105b')),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a46da1f0-856d-475c-9a21-80e2546e1f80'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='id',
            field=models.UUIDField(default=uuid.UUID('be4781d5-c500-49b8-a68d-e4f599cdeac1'), primary_key=True, serialize=False),
        ),
    ]
