# Generated by Django 4.0.3 on 2022-05-01 03:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0039_alter_cartitem_id_alter_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='id',
            field=models.UUIDField(default=uuid.UUID('14b5052c-6e22-4b1a-ab04-2c71c536e2c2'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ae53d0ad-6b76-47b5-a58a-50579c2e99a6'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_reference',
            field=models.UUIDField(default=uuid.UUID('537cb2ad-2f22-48c4-a9d6-9ba7ebd1afc0')),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='id',
            field=models.UUIDField(default=uuid.UUID('84e49bbe-ee0f-4796-a026-5b0f392715a5'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='id',
            field=models.UUIDField(default=uuid.UUID('33df8f5d-1049-42a9-b8b5-85562f014650'), primary_key=True, serialize=False),
        ),
    ]
