# Generated by Django 4.0.3 on 2022-05-01 03:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0040_alter_cartitem_id_alter_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3b611e68-3c9d-4d3a-9f45-dc7a34a37ebe'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.UUID('17ee5529-9f6a-4bd0-8b84-eff9768dbd7a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_reference',
            field=models.UUIDField(default=uuid.UUID('adc700c7-4c4b-4314-bfa3-e5f381f98487')),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c7f76a21-ad33-4a43-8f32-5e87705fe0a3'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f8e81d3c-b46d-4688-a85d-9f2e8db1b6d9'), primary_key=True, serialize=False),
        ),
    ]
