# Generated by Django 4.0.3 on 2022-05-01 04:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0042_alter_cartitem_id_alter_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_reference',
            field=models.UUIDField(default=uuid.UUID('b11433b5-8f6c-4ee1-8b6b-aef7e98790eb')),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e0c763e0-df75-4368-8436-3037364d08e9'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='id',
            field=models.UUIDField(default=uuid.UUID('224c9f20-9943-4717-b77e-032668e00802'), primary_key=True, serialize=False),
        ),
    ]
