# Generated by Django 4.0.3 on 2022-05-01 05:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0043_alter_order_order_reference_alter_shippingaddress_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_reference',
            field=models.UUIDField(default=uuid.UUID('cfd70d80-84a8-42d5-8f95-b76a49c355c5')),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e5be576f-f25b-4a1a-8c3e-90b4c33707f9'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b6531611-821e-4147-bccc-64fad667b469'), primary_key=True, serialize=False),
        ),
    ]
