# Generated by Django 4.0.3 on 2022-05-07 06:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0046_alter_order_order_reference_alter_wishlist_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='district',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_reference',
            field=models.UUIDField(default=uuid.UUID('76a1fd6a-e17d-4fb4-8add-39aad9bb9d91')),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='city',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='country',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='details',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='state',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
