# Generated by Django 4.0.3 on 2022-05-08 08:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0053_alter_order_cart_alter_order_order_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_reference',
            field=models.UUIDField(default=uuid.UUID('7589ab7a-f1ab-4028-ab1e-2375d9e9721c')),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='primary',
            field=models.BooleanField(default=True),
        ),
    ]
