# Generated by Django 4.0.3 on 2022-05-09 05:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0056_remove_order_address_order_addresse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_reference',
            field=models.UUIDField(default=uuid.UUID('a469d2bf-9e01-4e33-8f35-77fdc73e7628')),
        ),
    ]
