# Generated by Django 4.0.3 on 2022-05-11 02:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0061_alter_shippingaddress_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='itemss',
        ),
        migrations.AlterField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_reference',
            field=models.UUIDField(default=uuid.UUID('fcf0f7a6-7509-4582-b226-9827d7dc7ceb')),
        ),
    ]
