# Generated by Django 4.0.3 on 2022-05-11 11:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0063_alter_order_delivered_at_alter_order_order_reference_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ordered_at',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_reference',
            field=models.UUIDField(default=uuid.UUID('5c1788d2-adbb-4f0c-a7c1-30dcd5133d42')),
        ),
    ]
