# Generated by Django 4.0.3 on 2022-05-11 11:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0064_remove_order_ordered_at_alter_order_order_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_reference',
            field=models.UUIDField(default=uuid.UUID('0c24299a-5b04-45c7-8c87-fc4246c87e2e')),
        ),
    ]
