# Generated by Django 4.0.3 on 2022-05-11 13:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0069_alter_order_cart_alter_order_order_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_reference',
            field=models.UUIDField(default=uuid.UUID('659687f0-a06d-476c-bb8e-efaf8e246521')),
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='cartItems',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cartItems',
            field=models.ManyToManyField(to='orders.cartitem'),
        ),
    ]
