# Generated by Django 4.0.3 on 2022-05-11 15:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0074_remove_orderitem_user_orderitem_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_reference',
            field=models.UUIDField(default=uuid.UUID('d4290c75-fb43-41a9-9493-6317cffed7ac')),
        ),
    ]
