# Generated by Django 4.0.3 on 2022-05-11 15:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0075_alter_order_order_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_reference',
            field=models.UUIDField(default=uuid.UUID('29236dda-84b8-43b1-9d3c-3e69b0b486c5')),
        ),
    ]
