# Generated by Django 4.0.3 on 2022-05-12 14:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0099_alter_product_sku'),
        ('orders', '0079_remove_orderitem_user_orderitem_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_reference',
            field=models.UUIDField(default=uuid.UUID('09bc775c-f8d1-466d-96a3-3db60aab513f')),
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ManyToManyField(to='mart.product'),
        ),
    ]
