# Generated by Django 4.0.3 on 2022-05-12 15:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0100_alter_product_sku'),
        ('orders', '0080_alter_order_order_reference_remove_orderitem_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='mart.product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.ManyToManyField(to='orders.cartitem'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_reference',
            field=models.UUIDField(default=uuid.UUID('0ce65568-25e7-4b97-991f-08297cfb3e72')),
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mart.product'),
        ),
    ]
