# Generated by Django 4.0.3 on 2022-05-12 16:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0081_order_products_alter_order_cart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_reference',
            field=models.UUIDField(default=uuid.UUID('9c3cc80f-032a-4814-9bb4-dc30bb54b9cd')),
        ),
    ]
