# Generated by Django 4.0.3 on 2022-05-13 10:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0082_remove_order_cart_alter_order_order_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_reference',
            field=models.UUIDField(default=uuid.UUID('8f1db088-777a-473c-ae2f-58f9ebff6a2e')),
        ),
    ]
