# Generated by Django 4.0.3 on 2022-05-14 21:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0104_alter_product_sku'),
        ('orders', '0084_alter_order_order_reference_alter_order_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_reference',
            field=models.UUIDField(default=uuid.UUID('16ac6edb-1d95-44e8-be36-add2da810b7d')),
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ManyToManyField(blank=True, to='mart.product'),
        ),
    ]
