# Generated by Django 4.0.3 on 2022-05-15 11:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0086_alter_order_order_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='order_item',
            field=models.ManyToManyField(blank=True, to='orders.orderitem'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_reference',
            field=models.UUIDField(default=uuid.UUID('e8404d0a-f40e-4724-9f9c-aa7309ffc992')),
        ),
    ]
