# Generated by Django 4.0.3 on 2022-05-15 11:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0087_remove_orderitem_order_order_order_item_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_item',
            new_name='products',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_reference',
            field=models.UUIDField(default=uuid.UUID('b5a9771d-c2dc-4786-9d2f-aafce487f33a')),
        ),
    ]
