# Generated by Django 4.0.3 on 2022-05-15 13:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0090_remove_order_products_order_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_reference',
            field=models.UUIDField(default=uuid.UUID('77ef2616-9d96-4801-8b34-d6de860ec739')),
        ),
    ]
