# Generated by Django 4.0.3 on 2022-07-15 12:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0093_order_amount_alter_order_order_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_reference',
            field=models.UUIDField(default=uuid.UUID('ad8e2f5d-501d-4d65-b083-d6ac56c88957')),
        ),
    ]
