# Generated by Django 4.0.3 on 2022-07-15 12:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0094_alter_order_order_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_reference',
            field=models.UUIDField(default=uuid.UUID('afd5d973-f64c-4281-8575-cd7993565cf7')),
        ),
    ]
