# Generated by Django 4.0.3 on 2022-07-16 16:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0099_alter_order_order_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_reference',
            field=models.UUIDField(default=uuid.UUID('7ebeaab6-e028-4326-9827-60ac226bd3b5')),
        ),
    ]
