# Generated by Django 4.0.3 on 2022-07-16 16:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0100_alter_order_order_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_reference',
            field=models.UUIDField(default=uuid.UUID('3f10f47e-fd1f-4a65-9ea0-b4e21f11cbd7')),
        ),
    ]
