# Generated by Django 4.0.3 on 2022-07-16 16:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0101_alter_order_order_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_reference',
            field=models.UUIDField(default=uuid.UUID('d564ec4d-995d-468b-98c5-c3d9308094c2')),
        ),
    ]
