# Generated by Django 4.0.3 on 2022-04-08 08:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0003_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.UUIDField(default=uuid.UUID('850ca14b-1ae1-480a-a989-750fef7c4813')),
        ),
    ]
