# Generated by Django 4.0.3 on 2022-04-08 09:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0006_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.UUIDField(default=uuid.UUID('e3304204-9381-4b72-a003-eb202019faac')),
        ),
    ]
