# Generated by Django 4.0.3 on 2022-04-10 14:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0007_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.UUIDField(default=uuid.UUID('0432a199-a6bd-4aab-a2ac-7abb24595580')),
        ),
    ]
