# Generated by Django 4.0.3 on 2022-04-10 14:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0008_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.UUIDField(default=uuid.UUID('c9694a5d-c2a3-4646-b192-bc738aa79dc4')),
        ),
    ]
