# Generated by Django 4.0.3 on 2022-04-10 14:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0009_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.UUIDField(default=uuid.UUID('e341125f-540d-48e6-b0e6-f2f9f218e36d')),
        ),
    ]
