# Generated by Django 4.0.3 on 2022-04-10 15:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0010_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.UUIDField(default=uuid.UUID('542d8cf8-43d0-4a8b-91d0-6a54229f148c')),
        ),
    ]
