# Generated by Django 4.0.3 on 2022-04-11 01:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0011_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.UUIDField(default=uuid.UUID('1100bb96-a678-4aae-83a9-620f23636bec')),
        ),
    ]
