# Generated by Django 4.0.3 on 2022-04-14 03:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0012_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.UUIDField(default=uuid.UUID('479479b5-11d5-4140-a0c4-29db052aff56')),
        ),
    ]
