# Generated by Django 4.0.3 on 2022-04-14 10:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0013_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.UUIDField(default=uuid.UUID('787e3ddc-d276-42c4-adf8-b0309f38a0f2')),
        ),
    ]
