# Generated by Django 4.0.3 on 2022-04-14 10:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0014_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.UUIDField(default=uuid.UUID('3aeffe50-4545-41e7-967b-62b3cf1836bf')),
        ),
    ]
