# Generated by Django 4.0.3 on 2022-04-14 13:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0016_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.UUIDField(default=uuid.UUID('d70b573f-6f98-4382-8be5-a02ed5a69042')),
        ),
    ]
