# Generated by Django 4.0.3 on 2022-04-17 08:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0020_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.UUIDField(default=uuid.UUID('a5fb75ac-01b8-423f-91c1-4841ff736879')),
        ),
    ]
