# Generated by Django 4.0.3 on 2022-04-18 00:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0021_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.UUIDField(default=uuid.UUID('034fb76b-e89b-41c3-8b3c-d0e4704fbece')),
        ),
    ]
