# Generated by Django 4.0.3 on 2022-04-18 13:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0022_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.UUIDField(default=uuid.UUID('878c9359-96a0-4cb6-ac0b-9b787ab113d3')),
        ),
    ]
