# Generated by Django 4.0.3 on 2022-04-18 13:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0023_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.UUIDField(default=uuid.UUID('e89d6068-3397-4521-aa1a-44cb0b9067bc')),
        ),
    ]
