# Generated by Django 4.0.3 on 2022-04-19 05:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0024_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.UUIDField(default=uuid.UUID('59f25554-03d7-46db-8c6a-d01576503d6c')),
        ),
    ]
