# Generated by Django 4.0.3 on 2022-04-23 14:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0034_alter_futuredimages_color_name_alter_product_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='futuredimages',
            name='color_name',
        ),
        migrations.AddField(
            model_name='futuredimages',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mart.colorsoption'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.UUIDField(default=uuid.UUID('ee13189f-546d-4b50-bdb7-a96f46099fce')),
        ),
    ]
