# Generated by Django 4.0.3 on 2022-04-23 15:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0035_remove_futuredimages_color_name_futuredimages_color_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='futuredimages',
            old_name='color',
            new_name='color_name',
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.UUIDField(default=uuid.UUID('8e88bfe1-1da3-4bd5-9d9f-3784eb236fbe')),
        ),
    ]
