# Generated by Django 4.0.3 on 2022-04-30 07:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0041_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.UUIDField(default=uuid.UUID('a6218da8-2365-46f3-9913-05779c575230')),
        ),
    ]
