# Generated by Django 4.0.3 on 2022-04-30 14:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0043_alter_comments_id_alter_futuredimages_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fd74c651-5d49-4fd8-b42b-bcfd81d61750'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='futuredimages',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7121c467-9a7c-4299-9ca1-fa840dd3fa33'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7b078548-ffd3-4800-8247-5fb8a9238a48'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.UUIDField(default=uuid.UUID('3ca32842-10dd-4d2e-b8ff-58e97f5d75ec')),
        ),
        migrations.AlterField(
            model_name='variant',
            name='id',
            field=models.UUIDField(default=uuid.UUID('71633c83-85cc-4327-8c5b-6493ff410a14'), primary_key=True, serialize=False),
        ),
    ]
