# Generated by Django 4.0.3 on 2022-04-30 14:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0044_alter_comments_id_alter_futuredimages_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorsoption',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c9c2c184-25b9-4b53-863f-8b3c865ca22e'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comments',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8846ec50-54d3-424d-a975-19c5d3dfbb6d'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='futuredimages',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3802d2cd-d0f8-4c44-aecc-5cea650910f5'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8613266e-2538-4809-9fbc-d1656434eb18'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.UUIDField(default=uuid.UUID('63c072fc-e987-49f8-b4f7-680d776ba83b')),
        ),
        migrations.AlterField(
            model_name='sizesoption',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4590d3cc-5901-4ed4-8977-c9b3606e64e1'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='variant',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4c5b2fd3-63be-4eb2-8913-78c73565b49d'), primary_key=True, serialize=False),
        ),
    ]
