# Generated by Django 4.0.3 on 2022-04-30 14:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0045_alter_colorsoption_id_alter_comments_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='color',
        ),
        migrations.AlterField(
            model_name='colorsoption',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ecb8b3c4-7236-4a7c-86fb-b7c51397e18d'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comments',
            name='id',
            field=models.UUIDField(default=uuid.UUID('892ea3a8-c969-4945-8d3c-f871bfa8dadd'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='futuredimages',
            name='id',
            field=models.UUIDField(default=uuid.UUID('68cbec54-9ea8-4078-9bd9-fdcd785aab4a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('22e8cae0-b620-4eb2-aea5-ab1e43344dbd'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.UUIDField(default=uuid.UUID('28824ffa-4c29-48f4-960f-1d80e88256d1')),
        ),
        migrations.AlterField(
            model_name='sizesoption',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ea800b0d-4ca2-477e-b4da-950fe66fc8b6'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='variant',
            name='id',
            field=models.UUIDField(default=uuid.UUID('844f8eb2-f03d-4fa1-9202-b1e494934ac8'), primary_key=True, serialize=False),
        ),
    ]
