# Generated by Django 4.0.3 on 2022-04-30 15:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0047_alter_colorsoption_id_alter_comments_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.UUIDField(default=uuid.UUID('b0a081a0-8af6-4685-9308-f4597bdd552e')),
        ),
        migrations.AlterField(
            model_name='variant',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6263f4b7-f7b5-4269-8c74-4d955a6ca352'), primary_key=True, serialize=False, unique=True),
        ),
    ]
