# Generated by Django 4.0.3 on 2022-05-01 01:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0049_alter_product_sku_alter_variant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.UUIDField(default=uuid.UUID('b51cd5e7-39b4-4579-9062-dedcfed650b1')),
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
