# Generated by Django 4.0.3 on 2022-05-01 01:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0050_alter_product_sku_delete_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.UUIDField(default=uuid.UUID('53dd651f-a07d-4def-92dc-03dfb0edb7d7')),
        ),
    ]
