# Generated by Django 4.0.3 on 2022-05-01 01:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0051_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.UUIDField(default=uuid.UUID('181c1cad-2c74-4508-a556-a3da2addc4f0')),
        ),
    ]
