# Generated by Django 4.0.3 on 2022-05-01 02:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0054_alter_comments_id_alter_product_id_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.UUIDField(default=uuid.UUID('3236e957-4940-4954-8341-eb0dc0384096')),
        ),
    ]
