# Generated by Django 4.0.3 on 2022-05-01 02:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0055_alter_product_id_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.UUIDField(default=uuid.UUID('82ff8c2f-4cf6-4468-b902-843fd789f9fb')),
        ),
    ]
