# Generated by Django 4.0.3 on 2022-05-01 03:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0060_alter_product_id_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.UUIDField(default=uuid.UUID('4e5f8762-3481-40c4-9c88-fa68f58fc46d')),
        ),
    ]
