# Generated by Django 4.0.3 on 2022-05-01 05:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0062_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.UUIDField(default=uuid.UUID('e878076f-0d24-4ea1-b796-c751d0e8b207')),
        ),
    ]
