# Generated by Django 4.0.3 on 2022-05-02 03:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0063_alter_product_sku'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='futuredimages',
            options={'verbose_name_plural': 'Detail Images'},
        ),
        migrations.AlterModelOptions(
            name='sliders',
            options={'verbose_name_plural': 'Sliders'},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterModelOptions(
            name='types',
            options={'verbose_name_plural': 'Types'},
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.UUIDField(default=uuid.UUID('42e71052-d6ca-4402-829b-3f67e0076252')),
        ),
    ]
