# Generated by Django 4.0.3 on 2022-05-07 06:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0065_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.UUIDField(default=uuid.UUID('5ce957f5-69af-499f-9b47-ec82b87d216c')),
        ),
    ]
