# Generated by Django 4.0.3 on 2022-05-07 12:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0067_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.UUIDField(default=uuid.UUID('5bc8db15-cfae-4c10-854f-1c7467c6710c')),
        ),
    ]
