# Generated by Django 4.0.3 on 2022-05-07 12:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0068_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.UUIDField(default=uuid.UUID('fb93f3ab-1a1c-4a09-8820-094182340559')),
        ),
    ]
