# Generated by Django 4.0.3 on 2022-05-07 12:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0069_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.UUIDField(default=uuid.UUID('ae797609-370c-4098-ba8e-df4c80b01699')),
        ),
    ]
