# Generated by Django 4.0.3 on 2022-05-08 05:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0071_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.UUIDField(default=uuid.UUID('788c3cd1-4289-4677-8870-afcadb7165c8')),
        ),
    ]
