# Generated by Django 4.0.3 on 2022-05-08 08:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0073_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.UUIDField(default=uuid.UUID('4c894e24-01f0-4078-9216-9bbf10f7d0e4')),
        ),
    ]
