# Generated by Django 4.0.3 on 2022-05-11 02:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0080_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.UUIDField(default=uuid.UUID('79d46c20-3f16-47c8-9e05-0c3cd619971d')),
        ),
    ]
