# Generated by Django 4.0.3 on 2022-05-11 10:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0081_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.UUIDField(default=uuid.UUID('0117ccb2-eff0-4ba4-9de8-a8e00f95ef6e')),
        ),
    ]
