# Generated by Django 4.0.3 on 2022-05-11 11:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0082_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.UUIDField(default=uuid.UUID('4db10bb6-d7c7-4eca-8203-e6f85dc5c973')),
        ),
    ]
