# Generated by Django 4.0.3 on 2022-05-11 11:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0083_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.UUIDField(default=uuid.UUID('37aa3d2f-510f-430a-809b-f6793f99217a')),
        ),
    ]
