# Generated by Django 4.0.3 on 2022-05-11 13:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0085_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.UUIDField(default=uuid.UUID('094da263-c7ad-4785-a30e-4b84240d970f')),
        ),
    ]
