# Generated by Django 4.0.3 on 2022-05-11 13:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0086_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.UUIDField(default=uuid.UUID('c3a9771c-2cff-4a82-ac20-79f1de9e97bf')),
        ),
    ]
