# Generated by Django 4.0.3 on 2022-05-11 13:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0087_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.UUIDField(default=uuid.UUID('bcf8a14a-70ad-4bfb-aea4-d05a44d6f65d')),
        ),
    ]
