# Generated by Django 4.0.3 on 2022-05-11 13:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0088_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.UUIDField(default=uuid.UUID('6449d968-7d13-40b4-b364-b437f0af7597')),
        ),
    ]
