# Generated by Django 4.0.3 on 2022-05-11 14:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0090_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.UUIDField(default=uuid.UUID('79650c74-ffd0-4dde-b749-574d2d9deb13')),
        ),
    ]
