# Generated by Django 4.0.3 on 2022-05-11 15:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0093_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.UUIDField(default=uuid.UUID('78140bfe-9f65-4a3b-9761-dc65e0e12ca4')),
        ),
    ]
