# Generated by Django 4.0.3 on 2022-05-11 15:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0094_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.UUIDField(default=uuid.UUID('b365569d-1aa3-43b2-b6f4-8c0fa06a21f6')),
        ),
    ]
