# Generated by Django 4.0.3 on 2022-05-11 16:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0096_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.UUIDField(default=uuid.UUID('eba2f275-c140-459a-a468-d684586b188a')),
        ),
    ]
