# Generated by Django 4.0.3 on 2022-05-12 13:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0097_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.UUIDField(default=uuid.UUID('d33ef394-a4f3-4c71-995c-22ff72923069')),
        ),
    ]
