# Generated by Django 4.0.3 on 2022-05-12 14:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0098_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.UUIDField(default=uuid.UUID('e146bead-f2f6-4d51-ba69-5c347077ab52')),
        ),
    ]
