# Generated by Django 4.0.3 on 2022-05-12 15:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0099_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.UUIDField(default=uuid.UUID('0d760600-4327-4915-b006-bffe4c1d131b')),
        ),
    ]
