# Generated by Django 4.0.3 on 2022-05-13 10:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0101_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.UUIDField(default=uuid.UUID('e342c808-855c-4ec6-a149-b25e9ac20628')),
        ),
    ]
