# Generated by Django 4.0.3 on 2022-05-15 11:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0105_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.UUIDField(default=uuid.UUID('cea37bd5-8f93-4e15-a91a-06296af06f8a')),
        ),
    ]
