# Generated by Django 4.0.3 on 2022-05-15 11:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0106_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.UUIDField(default=uuid.UUID('cf70559b-0db4-4659-908f-d3e525f28a5d')),
        ),
    ]
