# Generated by Django 4.0.3 on 2022-05-15 12:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0108_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.UUIDField(default=uuid.UUID('e242ea3a-2da5-49a8-9fbb-aa7a8873c7d8')),
        ),
    ]
