# Generated by Django 4.0.3 on 2022-05-15 13:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0109_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.UUIDField(default=uuid.UUID('25b945c0-637e-45f7-9a6b-c98104af09ab')),
        ),
    ]
