# Generated by Django 4.0.3 on 2022-07-15 12:50

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mart', '0112_alter_product_sku'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Review',
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.UUIDField(default=uuid.UUID('d9b4bef0-4999-49ea-844f-f9363fca22c0')),
        ),
    ]
