# Generated by Django 4.0.3 on 2022-07-16 16:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0117_alter_product_sku_alter_review_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.UUIDField(default=uuid.UUID('f421b502-dcca-4436-8985-b4df98ccee2e')),
        ),
    ]
