# Generated by Django 4.0.3 on 2022-07-16 16:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0118_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.UUIDField(default=uuid.UUID('5352fa97-417d-477e-830b-afb0ab62f6a8')),
        ),
    ]
