# Generated by Django 4.0.3 on 2022-07-16 16:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0119_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.UUIDField(default=uuid.UUID('b83ae262-e887-4709-b6dd-76e510a75e7a')),
        ),
    ]
