# Generated by Django 4.0.3 on 2022-07-16 16:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0120_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.UUIDField(default=uuid.UUID('5cd2ad4b-2595-4dbe-a809-93a90d86964a')),
        ),
    ]
